env:
  es6: true
  browser: true
  commonjs: true
  jest: true
  node: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parser: 'babel-eslint'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 9
  sourceType: module

plugins: ['react', 'import']

settings:
  react:
    version: '16'

rules:
  import/no-named-as-default-member: 0
  import/no-named-as-default: 0
